Kirkstone update to 2024.9.0
chargebyte/meta-chargebyte-everest pull request #27
Opened 2024-10-28 15:04 UTC by mooraby

- Adaptations for EVerest 2024.9.0 release
- Introduce ISO15118-20 functionaliy which is not part of the release

2024-10-28 15:05 UTC, mooraby commented
Should be merged after https://github.com/EVerest/meta-everest/pull/39

2024-10-30 10:39 UTC, FaHaGit approved these changes

2024-10-30 10:48 UTC, barsnick approved these changes

2024-10-30 10:49 UTC, mhei requested changes
Update to 2024.09.0 of remotechargeport is missing and should be included IMHO.

2024-10-30 11:07 UTC, mhei approved these changes

2024-10-30 13:54 UTC, FaHaGit approved these changes

2024-10-30 14:52 UTC, merged